trigger:
  - main  # or your default branch

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'
    
    - script: npm install
      displayName: 'npm install'
    
    - script: npm run build
      displayName: 'Build project'

    - task: CopyFiles@2
      inputs:
        contents: '**'
        targetFolder: '$(Build.ArtifactStagingDirectory)'
      displayName: 'Copy Files to Staging Directory'
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
      displayName: 'Publish Artifact'
